Source code refining and cleaning
mpeg5/ffevc pull request #29
Opened 2022-04-07 13:22 UTC by dkozinski

Removed useless source code sections
Improved comments lines

2022-04-07 15:07 UTC, dariusz-f requested changes

2022-04-07 15:07 UTC, dariusz-f commented on ffmpeg-subtree/libavcodec/libxeve.c
> +    return 0;
add empty line before return

2022-04-07 15:07 UTC, dariusz-f commented on ffmpeg-subtree/libavcodec/libxeve.c
>      return 0;
add empty line before return

2022-04-07 15:07 UTC, dariusz-f commented on ffmpeg-subtree/libavcodec/libxeve.c
> + * @brief Switch encodet to bumping mode
encodet -> encoder

2022-04-07 15:07 UTC, dariusz-f commented on ffmpeg-subtree/libavcodec/libxeve.c
> + * @param id XEVE encodec instance identifier
encodec -> encoder

2022-04-07 15:07 UTC, dariusz-f commented on ffmpeg-subtree/libavcodec/libxeve.c
>      return 0;
add empty line before return, and the same in return below

2022-04-08 07:15 UTC, dkozinski commented on ffmpeg-subtree/libavcodec/libxeve.c
>      return 0;
Done

2022-04-08 07:15 UTC, dkozinski commented on ffmpeg-subtree/libavcodec/libxeve.c
> + * @brief Switch encodet to bumping mode
Done

2022-04-08 07:15 UTC, dkozinski commented on ffmpeg-subtree/libavcodec/libxeve.c
> + * @param id XEVE encodec instance identifier
Done

2022-04-08 07:16 UTC, dkozinski commented on ffmpeg-subtree/libavcodec/libxeve.c
>      return 0;
Done

2022-04-08 07:30 UTC, dariusz-f approved these changes
good

2022-04-08 07:31 UTC, merged